### ISSUE TITLE
cant use the gradlew command

### ISSUE THREAD

**Issue by OneTimeMission** [HumanDuck23/duck-dueller-v2#2]
![image](https://user-images.githubusercontent.com/113663390/190853775-3fe74b91-dfa7-43d8-89d8-cd511a31d7ec.png)

**Comment by HumanDuck23** [comment]
I've had the same issue, fixed it by using `.\gradlew.bat` instead of just `gradlew.bat`. Let me know how it goes.

**Comment by OneTimeMission** [comment]
now i have this issue

![image](https://user-images.githubusercontent.com/113663390/190855325-1e209488-0d4e-4927-8e6f-526dacf6ac16.png)

**Comment by HumanDuck23** [comment]
What is the error? I can't help you if I don't see what the problem is.

**Comment by OneTimeMission** [comment]
![image](https://user-images.githubusercontent.com/113663390/190855449-66bd99ab-7026-4932-bc82-463f8da26588.png)
how can i exatcly find the issiue

**Comment by OneTimeMission** [comment]
![image](https://user-images.githubusercontent.com/113663390/190855509-4a583144-0516-48dc-89b2-f54253385074.png)
maybe this helps?

**Comment by HumanDuck23** [comment]
> ![image](https://user-images.githubusercontent.com/113663390/190855449-66bd99ab-7026-4932-bc82-463f8da26588.png) how can i exatcly find the issiue

that's good, I've had this issue before, I'll find the solution and get back to you in a bit

**Comment by HumanDuck23** [comment]
Can you answer these questions please?

- What version of the Java JDK do you have installed?
- What is the output of running `echo %JAVA_HOME%` in CMD, and `echo $env:JAVA_HOME` in PowerShell?
- What is the contents of the `gradle.properties` file in the folder you're running `./gradlew.bat` in?

**Comment by OneTimeMission** [comment]
i reïnstalled java 2 days ago so newest version prob
![image](https://user-images.githubusercontent.com/113663390/190855818-a9f2390a-ab31-491d-a620-456e0968a5bd.png)

![image](https://user-images.githubusercontent.com/113663390/190855831-a35ede2b-af22-46ad-91a1-b8c55ff23d87.png)
![image](https://user-images.githubusercontent.com/113663390/190855864-8bc52cb8-c768-4bb0-805b-e603d16e6eb8.png)

**Comment by HumanDuck23** [comment]
Alright, you're gonna need to get a JDK version 8, not the newest. Here's the one I recommend: https://adoptium.net/temurin/releases/?version=8

In the installed there will be an option to have it set the JAVA_HOME variable, make sure to enable that or you'll have to do it yourself later. Let me know if you can run the command after the installation has completed.

**Comment by OneTimeMission** [comment]
![image](https://user-images.githubusercontent.com/113663390/190856512-9f753045-5d6a-473d-b159-7710a26815a4.png)
one step further nice

**Comment by OneTimeMission** [comment]
![image](https://user-images.githubusercontent.com/113663390/190856669-534790b7-4a4a-4dc4-9c86-6981741d5ffa.png)
i cant find the mod in the folder, is there something else i need to do first?

**Comment by HumanDuck23** [comment]
Run `.\gradlew.bat build`, after that there is a JAR file in the build/libs/ folder. Just drop that into the .minecraft/mods/ folder and you're good to go.

**Comment by OneTimeMission** [comment]
i did that but still cant find the mod in forge

**Comment by HumanDuck23** [comment]
You put the jar file into the mods folder, launched forge and then it's not there?

**Comment by OneTimeMission** [comment]
I can look into it again when i am home

**Comment by OneTimeMission** [comment]
It works now thank you so much fore you're time =)
