### ISSUE TITLE
I know it's old and not updated anymore but can you post compiled ver?

### ISSUE THREAD

**Issue by vanishLLC** [HumanDuck23/duck-dueller-v2#3]
I know that i could use gradle and build it myself but os i am using rn dossen't allow me to use .msi at the moment (waiting for fix) and i can't use adoptium to install a JDK can you build it for me please?

**Comment by vanishLLC** [comment]
if released version isn't diffrent from source then please close the issue

**Comment by HumanDuck23** [comment]
The released version should be the newest one, nothing's been changed since then
