### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by Razzy52** [HumanDuck23/duck-dueller-v2#4]
Tested it today and nothing seemed to be happening? Am i missing something.

**Comment by HumanDuck23** [comment]
> Tested it today and nothing seemed to be happening? Am i missing something.

Some things definitely won't work anymore because of things like API changes, but in general it should still function. Did you get any errors? What exactly did you do in-game and with the mod?

**Comment by Razzy52** [comment]
Looks Like I hadn't toggled the bot on...
However, it doesn't seem to work on the sumo mode due to not being able to find stats. Still does this with Queue Dodging off

**Comment by HumanDuck23** [comment]
> Looks Like I hadn't toggled the bot on...
> However, it doesn't seem to work on the sumo mode due to not being able to find stats. Still does this with Queue Dodging off

Ah yeah, the dodging is a bit weird when it doesn't find stats, even when you turn all dodging options off, you can fork it and try to fix it yourself if you'd like, it probably wouldn't be very difficult.

**Comment by Razzy52** [comment]
where is the code responsible for this located?

**Comment by HumanDuck23** [comment]
There's a `handleStats` method in bot/BotBase.kt, pretty sure that's where this happens but it's been a while since I've looked at this code

**Comment by Razzy52** [comment]
![image](https://github.com/HumanDuck23/duck-dueller-v2/assets/101041312/f68d13db-7d6b-4c4b-a242-94f16eedc917)
Any idea how to fix this error?

**Comment by HumanDuck23** [comment]
Don't run --info, add it as an argument to the command you ran before

**Comment by Razzy52** [comment]
https://mclo.gs/xHEwKVD
